// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YURent.Data;

namespace YURent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YURent.Data.anuncio", b =>
                {
                    b.Property<int>("id_anuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("data_publicacao")
                        .HasColumnType("real");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extensao_imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("preco_dia")
                        .HasColumnType("real");

                    b.Property<int>("visualizacoes")
                        .HasColumnType("int");

                    b.HasKey("id_anuncio");

                    b.ToTable("Anuncio");
                });

            modelBuilder.Entity("YURent.Data.faturacao", b =>
                {
                    b.Property<int>("id_faturacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codigo_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.Property<string>("morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nif")
                        .HasColumnType("int");

                    b.Property<string>("nome_completo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_faturacao");

                    b.ToTable("Faturacao");
                });

            modelBuilder.Entity("YURent.Data.guardado", b =>
                {
                    b.Property<int>("id_guardado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_anuncio")
                        .HasColumnType("int");

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.HasKey("id_guardado");

                    b.ToTable("Guardado");
                });

            modelBuilder.Entity("YURent.Data.mensagem", b =>
                {
                    b.Property<int>("id_mensagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("conteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("fromseller")
                        .HasColumnType("bit");

                    b.Property<int>("id_anuncio")
                        .HasColumnType("int");

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.Property<bool>("vista")
                        .HasColumnType("bit");

                    b.HasKey("id_mensagem");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("YURent.Data.reservas", b =>
                {
                    b.Property<int>("id_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("cancelado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("data_fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_anuncio")
                        .HasColumnType("int");

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.Property<float>("preco")
                        .HasColumnType("real");

                    b.HasKey("id_reserva");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("YURent.Data.transacoes", b =>
                {
                    b.Property<int>("id_transacoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_reserva")
                        .HasColumnType("int");

                    b.HasKey("id_transacoes");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("YURent.Data.utilizador", b =>
                {
                    b.Property<int>("id_utilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("avatar_extensao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_utilizador");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("YURent.Data.verificacao", b =>
                {
                    b.Property<int>("id_verificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_utilizador")
                        .HasColumnType("int");

                    b.Property<int>("nif")
                        .HasColumnType("int");

                    b.Property<string>("num_cc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telemovel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_verificacao");

                    b.ToTable("Verificacao");
                });
#pragma warning restore 612, 618
        }
    }
}
